[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "paypal.subscriptions"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["paypal", "subscriptions", "plans","billing", "payments", "recurring", "connector",]
icon = "icon.png"

repository = "https://github.com/ballerina-platform/module-ballerinax-paypal.subscriptions"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
