[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "paypal.subscriptions"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["paypal", "subscriptions", "plans","billing", "payments", "recurring", "connector",]
icon = "https://www.paypalobjects.com/webstatic/mktg/logo/pp_cc_mark_111x69.jpg"
repository = "https://github.com/ballerina-platform/module-ballerinax-paypal.subscriptions"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
